### ISSUE TITLE
BUG: No "content-type: application/json" in json on "token" endpoint resposes makes some clients fail, like "discourse"

### ISSUE THREAD

**Issue by raimon-segura** [rhertogh/yii2-oauth2-server#13] opened 2023-06-16 12:25 UTC
### What steps will reproduce the problem?
Make a request to yii oauth2 endpoint

### What is the expected result?
The response should has a content-type set to "application/json"

### What do you get instead?
For now I've added a hack inside discourse source files

I'm thinking to add that "content-type" to Controllers & Action source files.. any hint to start?

Many Thanks!

**Comment by rhertogh** [comment] 2023-06-17 18:02
@raimon-segura Hi, the default Yii Response overwrote the `Content-Type` header. This should now be fixed in `\rhertogh\Yii2Oauth2Server\helpers\Psr7Helper::psr7ToYiiResponse()` by setting the `Response::$format` to 'raw'.
Could you please confirm the issue is fixed in the latest `dev-master` version?

**Closed** 2023-06-19 07:33 UTC
Labels: bug

**Comment by raimon-segura** [comment] 2023-06-19 09:44
Thanks!
